import { encodeFunctionData, parseUnits } from 'viem';
import { CONTRACT_ADDRESSES } from '../constants/contracts';
import { ERC20_ABI, LENDING_POOL_ABI, VE_CENTRY_ABI } from '../constants/abis';
import { SWAP_MARKETS } from '../constants/markets';

export const AGENT_ACTIONS = Object.freeze({ SUPPLY:'lending.supply', WITHDRAW:'lending.withdraw', BORROW:'lending.borrow', REPAY:'lending.repay', APPROVE_ASSET:'token.approve', APPROVE_CENT:'token.approveCent', CREATE_LOCK:'governance.createLock', INCREASE_LOCK:'governance.increaseLock', EXTEND_LOCK:'governance.extendLock', WITHDRAW_LOCK:'governance.withdrawLock', CLAIM_REWARD:'rewards.claim', SWAP:'swap', BRIDGE:'bridge', GATEWAY_FUND:'gateway.fund' });
const ACTION_LABELS = { [AGENT_ACTIONS.SUPPLY]:'Supply',[AGENT_ACTIONS.WITHDRAW]:'Withdraw',[AGENT_ACTIONS.BORROW]:'Borrow',[AGENT_ACTIONS.REPAY]:'Repay',[AGENT_ACTIONS.APPROVE_ASSET]:'Approve token',[AGENT_ACTIONS.APPROVE_CENT]:'Approve CENT',[AGENT_ACTIONS.CREATE_LOCK]:'Create veCENT lock',[AGENT_ACTIONS.INCREASE_LOCK]:'Increase veCENT lock',[AGENT_ACTIONS.EXTEND_LOCK]:'Extend veCENT lock',[AGENT_ACTIONS.WITHDRAW_LOCK]:'Withdraw veCENT lock',[AGENT_ACTIONS.CLAIM_REWARD]:'Claim reward',[AGENT_ACTIONS.SWAP]:'Swap',[AGENT_ACTIONS.BRIDGE]:'Bridge USDC',[AGENT_ACTIONS.GATEWAY_FUND]:'Fund Arc through Gateway' };
const VALID_TOKEN_ADDRESSES = new Set(SWAP_MARKETS.map((m)=>String(m.address||'').toLowerCase()).filter(Boolean));
const VALID_LENDING_ADDRESSES = new Set(SWAP_MARKETS.filter((m)=>!m.swapOnly).map((m)=>String(m.address||'').toLowerCase()).filter(Boolean));

export function validateAgentPlan(plan){
  if(!plan||!Array.isArray(plan.actions)) return {ok:false,error:'No executable action plan was returned.'};
  if(!plan.actions.length) return {ok:false,error:'The request does not contain an executable site action.'};
  if(plan.actions.length>6) return {ok:false,error:'The requested action plan is too large.'};
  for(const action of plan.actions){
    if(!ACTION_LABELS[action?.type]) return {ok:false,error:`Unsupported action: ${action?.type||'unknown'}.`};
    if([AGENT_ACTIONS.SUPPLY,AGENT_ACTIONS.WITHDRAW,AGENT_ACTIONS.BORROW,AGENT_ACTIONS.REPAY].includes(action?.type)&&!VALID_LENDING_ADDRESSES.has(String(action.asset||'').toLowerCase())) return {ok:false,error:'The requested lending asset is not a configured Centry market.'};
    if(action?.type===AGENT_ACTIONS.APPROVE_ASSET&&!VALID_TOKEN_ADDRESSES.has(String(action.asset||'').toLowerCase())) return {ok:false,error:'The requested token is not a configured Centry asset.'};
    if(action?.type===AGENT_ACTIONS.SWAP&&(!VALID_TOKEN_ADDRESSES.has(String(action.inputToken||'').toLowerCase())||!VALID_TOKEN_ADDRESSES.has(String(action.outputToken||'').toLowerCase()))) return {ok:false,error:'The requested swap token is not supported by Centry.'};
    if(action?.type===AGENT_ACTIONS.BRIDGE&&(!['arc','base','arbitrum','ethereum'].includes(String(action.fromChain).toLowerCase())||!['arc','base','arbitrum','ethereum'].includes(String(action.toChain).toLowerCase()))) return {ok:false,error:'The requested bridge route is not supported.'};
    if(action?.type===AGENT_ACTIONS.GATEWAY_FUND&&(!action.amount||Number(action.amount)<=0)) return {ok:false,error:'Gateway funding requires a positive amount.'};
  }
  return {ok:true};
}
export function describeAgentAction(action){const label=ACTION_LABELS[action?.type]||'Transaction';const d=[];if(action?.amount)d.push(`${action.amount}${action.assetSymbol?` ${action.assetSymbol}`:''}`);if(action?.inputSymbol&&action?.outputSymbol)d.push(`${action.inputSymbol} → ${action.outputSymbol}`);if(action?.fromChain&&action?.toChain)d.push(`${action.fromChain} → ${action.toChain}`);if(action?.weeks)d.push(`${action.weeks} weeks`);if(action?.tokenId!=null)d.push(`veCENT #${action.tokenId}`);return `${label}${d.length?` · ${d.join(' · ')}`:''}`;}
export function buildAgentWalletRequest(action){const type=action?.type,amount=action?.amount;if([AGENT_ACTIONS.SUPPLY,AGENT_ACTIONS.WITHDRAW,AGENT_ACTIONS.BORROW,AGENT_ACTIONS.REPAY].includes(type))return{to:CONTRACT_ADDRESSES.lendingPool,data:encodeFunctionData({abi:LENDING_POOL_ABI,functionName:type.split('.')[1],args:[action.asset,parseUnits(String(amount),Number(action.decimals??6))]}),value:0n};if(type===AGENT_ACTIONS.APPROVE_ASSET)return{to:action.asset,data:encodeFunctionData({abi:ERC20_ABI,functionName:'approve',args:[CONTRACT_ADDRESSES.lendingPool,parseUnits(String(amount),Number(action.decimals??6))]}),value:0n};if(type===AGENT_ACTIONS.APPROVE_CENT)return{to:CONTRACT_ADDRESSES.centryToken,data:encodeFunctionData({abi:ERC20_ABI,functionName:'approve',args:[CONTRACT_ADDRESSES.veCentry,parseUnits(String(amount),18)]}),value:0n};if(type===AGENT_ACTIONS.CREATE_LOCK)return{to:CONTRACT_ADDRESSES.veCentry,data:encodeFunctionData({abi:VE_CENTRY_ABI,functionName:'createLock',args:[parseUnits(String(amount),18),BigInt(action.weeks)*604800n]}),value:0n};if(type===AGENT_ACTIONS.INCREASE_LOCK)return{to:CONTRACT_ADDRESSES.veCentry,data:encodeFunctionData({abi:VE_CENTRY_ABI,functionName:'increaseAmount',args:[BigInt(action.tokenId),parseUnits(String(amount),18)]}),value:0n};if(type===AGENT_ACTIONS.EXTEND_LOCK)return{to:CONTRACT_ADDRESSES.veCentry,data:encodeFunctionData({abi:VE_CENTRY_ABI,functionName:'extendLock',args:[BigInt(action.tokenId),BigInt(action.weeks)*604800n]}),value:0n};if(type===AGENT_ACTIONS.WITHDRAW_LOCK)return{to:CONTRACT_ADDRESSES.veCentry,data:encodeFunctionData({abi:VE_CENTRY_ABI,functionName:'withdraw',args:[BigInt(action.tokenId)]}),value:0n};return null;}
